### ISSUE TITLE
Question about 3d keypoint data.

### ISSUE THREAD

**Issue by Neo0214** [wholebody3d/wholebody3d#16]
When I using keypoints_3d in RGBto3D_train.json, I found that x or y value may be -1400 or less(body part, 0-16).  Is the unit of measurement for the data millimeters? Where is the origin of the coordinates? I seem to not have found a clear answer in the data description.
If anyone can help me, thank you very much.

**Comment by Zhuyue0324** [comment]
We recorded the value in millimeter. You can justify easily the unit of our data by: if it is generally <10, then its in meter; if it is generally >100, then its in millimeter

As for origin, if you want to project 3D coordinates into 2D, please check the closed issue 5 and 6, and I also past the answer here too: The 3d keypoints in RGBto3D_train.json are actually R_cam * X_global, so you don't need R_cam but you need T_cam to project correctly into 2D.
The 2d keypoints are X=K_cam(R_cam * X_global + T_cam) then X[:, :, :2] /= X[:, :, 2:3] is the 2D coordinates

Otherwise, if you just want to do training and evaluation without 2D, then the position of the origin is not important, since our proposed evaluation are always pelvis aligned (global translation ignored)

**Comment by nerminsamet** [comment]
Alternatively, you could also download H3WB dataset in a format commonly employed for 3D pose estimation tasks [here](https://drive.google.com/file/d/1LZh4Jsg3_ZKBF0iEPiexzoGHE4srLgfC/view?usp=share_link).
We provide an accompanying [data preparation class](https://github.com/wholebody3d/wholebody3d/blob/main/utils/prepare_data_h3wb.py) for this format. We also recommend this format for your experiments.

In this format all 3D keypoints are in global coordinate system.

**Comment by Neo0214** [comment]
@Zhuyue0324 I want to use 3D_global, so I just need to figure out R_cam and then use it to divide x,y,z data. Am I correct?

**Comment by Zhuyue0324** [comment]
Yes, you are right. Or you just use the data which @nerminsamet has provided, which directly has 3D global coordinates
