### ISSUE TITLE
about the hand dataset

### ISSUE THREAD

**Issue by lsl136** [wholebody3d/wholebody3d#2]
hello,could you please tell me how to get the small datasets about hand which you mentioned in the paper?

**Comment by Zhuyue0324** [comment]
After we have applied Openpifpaf on images, for each image, we check if at least one hand is fully detected which has all 21-joint 2D annotations. (These hands are not occluded, otherwise openpifpaf won't predict their positions). For such a hand we crop (x.min-50, y.min-50, x.max+50, y.max+50) region and reshape to 384x384 and save the cropped hand image, until we have enough number of samples we need (22k).

Same for the face

**Comment by lsl136** [comment]
Thanks very much.

**Comment by lsl136** [comment]
I would be grateful if you could post the dataset about the hand.

**Comment by Zhuyue0324** [comment]
I am sorry I think I couldn't, since they are the cropped images from original videos of Human3.6m dataset, which their copy right says " This product may only be used by you, and you may not rent, lease, lend, sub-license or transfer the dataset or any of your rights under this agreement to anyone else."
