### ISSUE TITLE
Why are people tilted when plotting the GT with 'draw_skeleton' function

### ISSUE THREAD

**Issue by luckcodingdog** [wholebody3d/wholebody3d#26]
![S5_Images_Directions 2 58860488_frame_1740](https://github.com/wholebody3d/wholebody3d/assets/10081813/93094972-3416-4d97-9a60-5da653aaab57)
![S5_Images_Directions 2 58860488_frame_1740_3d](https://github.com/wholebody3d/wholebody3d/assets/10081813/c607390e-5332-4e3e-b276-6b76b88fb97f)

We use the GT provided by you, the plotting 3d keypoint of the woman is tilted.
Why this happens? 
Thanks in advance for your reply.

**Comment by Zhuyue0324** [comment]
You can try the plot parameter pointsize=1

**Comment by luckcodingdog** [comment]
Thanks for your quick reply @Zhuyue0324 .
But after i modify with your suggestion, the result is also tilted.
"    draw_skeleton(keypoints_3d_float, pointsize=1, plt_show=True, save_path=plot_gt_3d_path)
"
![Uploading Figure_1.png…]()

**Comment by Zhuyue0324** [comment]
If you mean the human is not vertically straight, it is due to that I record 3D data as X_global * R_cam, which on one hand allowing a same facing orientation of human between 3D skeleton and the image, but on the other hand, the rotation of camera is included and they seems not filming horizontally by dataset default but about 10-15 degree looking down, leading to non-vertical pose in that view.

**Comment by luckcodingdog** [comment]
Thanks for your explanation.
