### ISSUE TITLE
Can you provide the code for training `Large SimpleBaseline` for 3D whole body lift  from complete 2D whole body keypoints (2D->3D)?

### ISSUE THREAD

**Issue by jiwei-dot** [wholebody3d/wholebody3d#3]
First, many thanks to the authors for providing such a rich dataset for 3D wholebody keypoints detection. 
I used the dataset you provided to implement the 2D hands keypoints lifting task, where the input is 42 x 2 dimensional 2D coordinate points of both hands and the output is 41 x 3 3D relative coordinates(relative to left hand root).
To implement it, I used the simplebaseline model provided by [mmpose](https://github.com/open-mmlab/mmpose/blob/master/configs/body/3d_kpt_sview_rgb_img/pose_lift/h36m/simplebaseline3d_h36m.md) for network training, where the training set was 2Dto3D_train_part1,2,3.json and tested on 2Dto3D_train_part4.json, but the MPJPE results on the test set were 1.678072452545166(m)，which is very different from the result in your paper.
If it is convenient, could you share your code in implementing it, here is my email address (weiji@zju.edu.cn) and I am looking forward to your reply.

**Comment by Zhuyue0324** [comment]
Hello, thank you for using our annotations. There are many differences between what you have tried and what we did. These are:

1. We never did a hand-only lifting task, but always wholebody. which means body positions could have some relative prior to the hands' positions 

2. The hand aligned metric is based on wrist of each hand, which means we align left hand with left wrist, as well as right hand with right hand wrist (which makes more sense for individual hand action). I wonder if your right hand general estimated positions are way too 'random' based on left hand root since there are not related at all.

3. In paper we reported evaluation score on test set (which we didn't release the groundtruth and hoping to make it a kind of 'leader-board') and reported in the appendix the cross validation score on train set. The cross validation we use a 20% validation 80% train strategy. The part 1,2,3 and 4 split is more for those whose training dataset is too big to load on there computer and might have 'out of memory' issue a walk-around to load training dataset, which is not our cross validation split. (But you remind me of probably providing a cross validation split in the future)

4. There are some switches between (m) and (mm) the training and test. The dataset is recorded in (mm) while we divided it by 1000(both 2D pixel and 3D mm) to train in (1000pixel->m), and finally multiplied the position by 1000 to return to (mm). You can pay attention to the unit you use.  

These are what I think might help. For some reasons the training code is temporally unable to be shared but will be public in the future. We apologize for current inconvenience

**Comment by jiwei-dot** [comment]
Thank you very much for your valuable reply, I will modify the code for the difference you mentioned above, and look forward to your disclosure of the training code in the future😉

**Comment by luckcodingdog** [comment]
Hi, @Zhuyue0324 
I also have the same question for training code. I want to reproduce the Transformer model, 
Could you share the training code? or Is there a schedule to share the training code?
Thanks in advance!
