### ISSUE TITLE
the visualize results is correct ?

### ISSUE THREAD

**Issue by canghaiyunfan** [wholebody3d/wholebody3d#4]
Thanks for your great work!

I visualize image with your anns, the results as follow, is it correct or not?
![image](https://user-images.githubusercontent.com/21115878/208579624-91482ef7-a124-46e7-9aad-5c54c392d7c3.png)

This is my visualize code:
```
import cv2
import json
from PIL import Image
from utils.utils import json_loader_part, json_loader, draw_skeleton


data_dir = '/data/dataset/whole-body/human3.6m/annotations'
keypoints_2d, keypoints_3d = json_loader_part(data_dir)
input_list, target_list, bbox_list = json_loader(data_dir, task=3, type='train')

i = 100
img = Image.open('/data/dataset/whole-body/human3.6m/' + input_list[i])
save_path = '1.jpg'

draw_skeleton(keypoints_2d[i], save_path=save_path, background=img)
```

**Comment by Zhuyue0324** [comment]
They are not correct, because they are not the matching image and annotation.

The samples being recorded are sorted by a '4 corner average error score' in the **complete** json file, the order of these samples from subjects are mixed, like first sample is from S5, second one is from S7, etc. However, the samples in each **part** json file are not, they are respectively only from S1, S5, S6 and S7 for part 1,2,3 and 4 under the same '4 corner average error score' order. Thus using json_load_part will make first 20k samples all from S1, then all from S5, etc. These two loading function don't match each other at same index position. (But somehow, if you pick every S1 samples from complete json file by order, they should match part1 json file, same for S5, S6 and S7)

While this is not a problem when you use part json train file for task 1 or 2 alone because both the complete file and part files consist of same 80k samples, just different order, we admit that it causes problem when you want to add 2D annotations to train task 3 with json_load_part loading.

I propose 3 different solutions for that:
1: Only use json_loader when you want image-2D matching
'''
keypoints_2d, keypoints_3d = json_loader(data_dir)
'''
2: create 4 lists and separate image lists into S1, S5, S6, S7 separately and concatenate them, then you can transform the complete file ordering into part file sample order. (do same thing for annotations and bounding boxes if you want simultaneously reorder them)
'''
list = [[], [], [], []]
for i in range(len(input_list)):
    if 'S1' in input_list[i]:
        list[0].append(input_list[i])
    elif 'S5' in input_list[i]:
        list[1].append(input_list[i])
    elif 'S6' in input_list[i]:
        list[2].append(input_list[i])
    elif 'S7' in input_list[i]:
        list[3].append(input_list[i])
input_list = list[0]+list[1]+list[2]+list[3]
'''
3: Wait for me to re-split complete json file into 4 part files (or more probably 5 part files to correspondent to the cross validation split in the paper, which is subject-mixed and have same order) I am pretty sure I will need to do this as more people will request cross-validation split to facilitate their work. But before it is released, please use former 2 solutions.

I hope this answer can help, and the final tips: put pointsize=1 to make the ploted point not that big.

**Comment by Zhuyue0324** [comment]
I update the new split 5 parts with each of them correspondent to cross validation 1 to 5, as well as json_loader_part function(). Now it works as:
cv=0, it has the same return as json_loader(data_path, task=1, type='train')
cv=1 2 .. or 5, it returns correspondent file's data
I hope this can now solve the problem.

**Comment by canghaiyunfan** [comment]
thanks, now the results is correct.
